### ISSUE TITLE
Eval nerf synthetic

### ISSUE THREAD

**Issue by BAI-tc** [liaozhanfeng/Spiking-NeRF#2]
Thanks!

**Comment by HuTaoMylove** [comment]
same question！

**Comment by ImmaFake** [comment]
same question, please provide us with the test code.

**Comment by ImmaFake** [comment]
Have you solved this problem?

**Comment by ImmaFake** [comment]
> Thanks!
Have you solved this problem?

**Comment by HuTaoMylove** [comment]
what kan I say？man！

**Comment by ImmaFake** [comment]
Have the author offered you the evaluation part?

**Comment by ImmaFake** [comment]
If so, could you please share it with us?

**Comment by BAI-tc** [comment]
> If so, could you please share it with us?

No, I don't use this dataset . I'm sorry I can't help you.

**Comment by HuTaoMylove** [comment]
from HFneus,PETneus,LODneus to Spiking NeRF,they all do not release the evaluation part.I have model ,but I don't know how to delete the mesh not be seen. So funny! just dream better score next paper!

**Comment by ImmaFake** [comment]
It seems like adding  --render_only and --render_test will load the evaluation code? Am I right?

> from HFneus,PETneus,LODneus to Spiking NeRF,they all do not release the evaluation part.I have model ,but I don't know how to delete the mesh not be seen. So funny! just dream better score next paper!

It seems like adding  --render_only and --render_test will load the evaluation code? Am I right?
